export const mockData = [
  {
    id: "1",
    title: "React 18 新功能完整指南",
    summary: "詳細介紹 React 18 的並發功能、Suspense 改進、自動批次處理等新特性，以及如何在專案中應用這些功能。",
    type: "link" as const,
    tags: ["React", "前端", "技術", "程式設計"],
    createdAt: new Date("2024-01-15T10:30:00"),
    thumbnail: "/placeholder.svg?height=128&width=256",
    url: "https://example.com/react18-guide",
  },
  {
    id: "2",
    title: "設計系統建構最佳實踐",
    summary: "從零開始建構企業級設計系統的完整流程，包含元件庫設計、文件撰寫、版本控制等實務經驗分享。",
    type: "document" as const,
    tags: ["設計系統", "UI/UX", "設計", "前端"],
    createdAt: new Date("2024-01-14T14:20:00"),
    thumbnail: "/placeholder.svg?height=128&width=256",
  },
  {
    id: "3",
    title: "現代網頁開發架構圖",
    summary: "展示現代全端網頁應用程式的完整架構，包含前端框架、後端 API、資料庫、部署流程等各個環節。",
    type: "image" as const,
    tags: ["架構", "全端", "開發", "技術"],
    createdAt: new Date("2024-01-13T09:15:00"),
    thumbnail: "/placeholder.svg?height=128&width=256",
  },
  {
    id: "4",
    title: "AI 輔助程式開發工具比較",
    summary: "比較 GitHub Copilot、TabNine、ChatGPT 等 AI 程式開發輔助工具的功能差異、使用體驗和適用場景。",
    type: "link" as const,
    tags: ["AI", "開發工具", "程式設計", "生產力"],
    createdAt: new Date("2024-01-12T16:45:00"),
    thumbnail: "/placeholder.svg?height=128&width=256",
  },
  {
    id: "5",
    title: "TypeScript 進階型別應用",
    summary: "深入探討 TypeScript 的進階型別功能，包含條件型別、映射型別、模板字面量型別等高級用法。",
    type: "document" as const,
    tags: ["TypeScript", "程式設計", "型別系統", "前端"],
    createdAt: new Date("2024-01-11T11:30:00"),
  },
  {
    id: "6",
    title: "微服務架構設計模式",
    summary: "介紹微服務架構中常見的設計模式，包含服務發現、熔斷器、分散式追蹤等關鍵概念和實作方式。",
    type: "link" as const,
    tags: ["微服務", "架構", "後端", "系統設計"],
    createdAt: new Date("2024-01-10T13:20:00"),
    thumbnail: "/placeholder.svg?height=128&width=256",
  },
]
